### ISSUE TITLE
Source error - com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.

### ISSUE THREAD

**Issue by paulmac97** [Baseflow/XamarinMediaManager#720]
## 🐛 Bug Report

Hi, thanks for providing the player! I'm facing an error while playing a .mp3 format audio file in my Xamarin.Forms project. Audio is not playing.

### Expected behavior
Play .mp3 audio file

### Reproduction steps
Pass mp3 audio URL from archive website in Play() method

### Configuration

**Version:** 
0.9.0 (I'm not using the latest version due to NotImplemented exception in 0.9.7)

**Platform:** 
- [x] Xamarin.Forms

**Error logs**
```
05-31 20:37:32.463 E/ExoPlayerImplInternal( 1393): Source error.
05-31 20:37:32.463 E/ExoPlayerImplInternal( 1393): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
05-31 20:37:32.463 E/ExoPlayerImplInternal( 1393): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
05-31 20:37:32.463 E/ExoPlayerImplInternal( 1393): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
05-31 20:37:32.463 E/ExoPlayerImplInternal( 1393): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
05-31 20:37:32.463 E/ExoPlayerImplInternal( 1393): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-31 20:37:32.463 E/ExoPlayerImplInternal( 1393): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-31 20:37:32.463 E/ExoPlayerImplInternal( 1393): 	at java.lang.Thread.run(Thread.java:761)
```

If this issue is resolved in a later release of MediaManager than what I'm using, then please let me know. Thanks!

Waiting for your reply..

**Comment by paulmac97** [comment]
Any updates please? Need help

**Comment by paulmac97** [comment]
Please note that another mp3 file from archive link was playing fine..

**Comment by paulmac97** [comment]
Extremely Sorry... the problem was that I had used the archive URL to be https://archive.org/**details**/..mp3 instead of using https://archive.org/**download**/...mp3 in the Play() method's parameter! After changing the URL with /download, the player is playing the mp3 audio fine.. Thank God for the solution. Thanks all!
