### ISSUE TITLE
System.NullReferenceException Xamarin forms Tizen

### ISSUE THREAD

**Issue by iptvstreamplayer** [Baseflow/XamarinMediaManager#728]
## 🐛 Bug Report

On Xamarin Forms Tizen

System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaManager.Forms.Platforms.Tizen.VideoViewRenderer.OnElementChanged(ElementChangedEventArgs`1 args)

### Configuration

Xamarin Forms 4.7.0

**Version:** 0.9.7

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ - ] :monkey: Xamarin.Forms

![Screenshot_1](https://user-images.githubusercontent.com/61454526/86891468-84d4b900-c11c-11ea-9cf5-85608d8daab1.png)

**Comment by iptvstreamplayer** [comment]
Its working fine in Xamarin forms Android but not working in Xamarin forms Tizen

System.NullReferenceException: Object reference not set to an instance of an object.
at MediaManager.Forms.Platforms.Tizen.VideoViewRenderer.OnElementChanged(ElementChangedEventArgs`1 args)

this error pn startup
