### ISSUE TITLE
Description cannot be null

### ISSUE THREAD

**Issue by MrSerWin** [Baseflow/XamarinMediaManager#753]
## 🐛 Bug Report
Description cannot be null
In my Logs I can see such error 
```
The object type cannot be specified "Mono.Debugger.Soft.PointerValue" to type "Mono.Debugger.Soft.PrimitiveValue".
```
and after that
```
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: Description cannot be null
	at android.support.v4.media.session.MediaSessionCompat$QueueItem.<init>(MediaSessionCompat.java:1962)
	at android.support.v4.media.session.MediaSessionCompat$QueueItem.<init>(MediaSessionCompat.java:1954)
	at com.google.android.exoplayer2.ext.mediasession.TimelineQueueNavigator.publishFloatingQueueWindow(TimelineQueueNavigator.java:226)
	at com.google.android.exoplayer2.ext.mediasession.TimelineQueueNavigator.onTimelineChanged(TimelineQueueNavigator.java:119)
	at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onTimelineChanged(MediaSessionConnector.java:1122)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$0$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:804)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$N_S5kRfhaRTAkH28P5luFgKnFjQ.invokeListener(lambda)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:802)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:683)
```
but there are no tracks (MediaItems) without description

### Expected behavior
should not crash application

### Configuration

**Version:** 1.0.1

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x ] :monkey: Xamarin.Forms

**Comment by MrSerWin** [comment]
`java.lang.IllegalArgumentException: Description cannot be null
android.support.v4.media.session.MediaSessionCompat$QueueItem.<init> MediaSessionCompat.java:1962
android.support.v4.media.session.MediaSessionCompat$QueueItem.<init> MediaSessionCompat.java:1954
com.google.android.exoplayer2.ext.mediasession.TimelineQueueNavigator.publishFloatingQueueWindow TimelineQueueNavigator.java:226
com.google.android.exoplayer2.ext.mediasession.TimelineQueueNavigator.onCurrentWindowIndexChanged TimelineQueueNavigator.java:126
com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onPositionDiscontinuity MediaSessionConnector.java:1159
com.google.android.exoplayer2.ExoPlayerImpl.lambda$seekTo$3 ExoPlayerImpl.java:362
com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$Or0VmpLdRqfIa3jPOGIz08ZWLAg.invokeListener(Unknown Source:0)
com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke BasePlayer.java:182
com.google.android.exoplayer2.ExoPlayerImpl.invokeAll ExoPlayerImpl.java:845
com.google.android.exoplayer2.ExoPlayerImpl.lambda$notifyListeners$6 ExoPlayerImpl.java:726
com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$DrcaME6RvvSdC72wmoYPUB4uP5w.run(Unknown Source:4)
com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners ExoPlayerImpl.java:736
com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners ExoPlayerImpl.java:726
com.google.android.exoplayer2.ExoPlayerImpl.seekTo ExoPlayerImpl.java:362
com.google.android.exoplayer2.SimpleExoPlayer.seekTo SimpleExoPlayer.java:1247
com.google.android.exoplayer2.DefaultControlDispatcher.dispatchSeekTo DefaultControlDispatcher.java:34
com.google.android.exoplayer2.ext.mediasession.TimelineQueueNavigator.onSkipToQueueItem TimelineQueueNavigator.java:163
com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onSkipToQueueItem MediaSessionConnector.java:1286
android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onSkipToQueueItem MediaSessionCompat.java:1554
android.media.session.MediaSession$CallbackMessageHandler.handleMessage MediaSession.java:1622
android.os.Handler.dispatchMessage Handler.java:107
android.os.Looper.loop Looper.java:214
android.app.ActivityThread.main ActivityThread.java:7386
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:492
com.android.internal.os.ZygoteInit.main ZygoteInit.java:980`

**Comment by MrSerWin** [comment]
1. start playing 
I fill queue with adding items to it 
`CrossMediaManager.Current.Queue.Add(track)`
and call 
```
await CrossMediaManager.Current.Play();
                or
await CrossMediaManager.Current.PlayQueueItem(trackIndex);
```
2. after track switched I chouse another playlist and trying play track
In this case I'm checking if playlist updated, if so, I'm update queue and starting selected track

**Comment by EddieNoureddine** [comment]
PlayQueueItem(int SelectedIndex) and all of its overloads is not working for me either, and it never worked in the previous versions. What I did as a workaround is that I always rearranged the collection or List to have the selected track at index 0; 

for some reason the selected index works only on index zero!; this is a bug

**Comment by MrSerWin** [comment]
**EddieNoureddine**, yeah, I fixed it this way too. but unfortunately there are no comments from lib authors in this thread

**Comment by Jack-Paul** [comment]
I am facing the same issue, but in my case, i don't add songs to queue, but play them one by one calling play("url"), any idea how to fix for my case?

**Comment by malek00** [comment]
Hello, the same problem with play('url')

**Comment by arahmancsd** [comment]
I solved this error with stopping and playing the new item. Before playing every media file, I am checking the state of the player and then load another file if I have to.

I used below condition. Although it may seem strange, but it worked.

```
if (CrossMediaManager.Current.IsPlaying() || CrossMediaManager.Current.State != MediaPlayerState.Stopped)
                await CrossMediaManager.Current.Stop();
```
// load or play another file

**Comment by EddieNoureddine** [comment]
@arahmancsd  if you use Stop() on a collection , you lose the ability to forward and back the  tracks in the notification panel outside, as it will show only on song that is currently playing , not the whole list of media items

**Comment by jari-kuipers** [comment]
I'm having the same issue with play("url").
Is there any workaround for this and/or will this ever be fixed?

**Comment by Jack-Paul** [comment]
Yes using Stop() causing a weird exception in my implementation, so I have reverted those changes, waiting and hoping for the issue to be fixed soon.

**Comment by janwiebe-jump** [comment]
I've been hit by this issue as well.
After some digging I found that [this method in the QueueNavigator](https://github.com/Baseflow/XamarinMediaManager/blob/a6b128667271e221218826dd2708b2fc42f9bc51/MediaManager/Platforms/Android/Queue/QueueNavigator.cs#L33) returns null, which causes the ExoPlayer to crash exception.
I'm not sure why the media item isn't pressent and can't be found.
During my debugging session, the Queue was empty.

**Comment by Jack-Paul** [comment]
Is there any way to fix this soon, because whenever my app crashed the only issue in the log file is due to this?

**Comment by janwiebe-jump** [comment]
I have hotfixed my fork of the MediaManager plugin, by adding a fallback method that I use to provide the MediaItem information in case the MediaManager can't provide it (hence the crash).
[See this commit](https://github.com/janwiebe-jump/XamarinMediaManager/commits/hotfix/retrieve-mediaitem)

**Comment by jamsoft** [comment]
@janwiebe-jump Can you put together a PR for this so we can test?

**Comment by janwiebe-jump** [comment]
@jamsoft Yes, see https://github.com/Baseflow/XamarinMediaManager/pull/822

**Comment by copang** [comment]
I hope this fix will be updated soon on nuget package. Thanks!

**Comment by janwiebe-jump** [comment]
@copang yes indeed. 
@jamsoft did you have the opportunity to test this?

Maybe @martijn00 can have a look?

**Comment by martijn00** [comment]
New release is out.
