### ISSUE TITLE
Java.Lang.IllegalStateException when play at startup

### ISSUE THREAD

**Issue by MichaelPeter** [Baseflow/XamarinMediaManager#767]
## 🐛 Bug Report

I start replay at startup, sometimes the app crashes with illegal state exception on android, wie exoplayer

The stacktrace from below is from version 0.9.7 there it almost always happend, but in the current version 1.0.4 it still happens but rarely. Is there a way to prevent this? Or check the state if the player is ready for playback?

Found just this regarding the error:
https://github.com/google/ExoPlayer/issues/4490

```


Unhandled Error: Java.Lang.IllegalStateException: Exception of type 'Java.Lang.IllegalStateException' was thrown.
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <89755ea61d9c4ae0a40ce90b872c9e2d>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <89755ea61d9c4ae0a40ce90b872c9e2d>:0
  at Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager.SetPlayer (Com.Google.Android.Exoplayer2.IPlayer player) [0x0002c] in C:\Users\mhvdi\Documents\OpenSource\ExoPlayerXamarin\ExoPlayer.UI\obj\Release\monoandroid90\generated\src\Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager.cs:1348
  at MediaManager.Platforms.Android.Notifications.NotificationManager.set_Player (Com.Google.Android.Exoplayer2.IPlayer value) [0x00007] in Z:\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\Notifications\NotificationManager.cs:28
  at MediaManager.Platforms.Android.Notifications.NotificationManager.UpdateNotification () [0x00025] in Z:\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\Notifications\NotificationManager.cs:71
  at MediaManager.Queue.MediaQueue.OnQueueChanged (System.Object s, MediaManager.Queue.QueueChangedEventArgs e) [0x00013] in Z:\Documents\OpenSource\XamarinMediaManager\MediaManager\Queue\MediaQueue.cs:124
  at MediaManager.Queue.MediaQueue.MediaItems_CollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00000] in Z:\Documents\OpenSource\XamarinMediaManager\MediaManager\Queue\MediaQueue.cs:44
  at (wrapper delegate-invoke) <Module>.invoke_void_object_NotifyCollectionChangedEventArgs(object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00018] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:263
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionReset () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:362
  at System.Collections.ObjectModel.ObservableCollection`1[T].ClearItems () [0x00018] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:166
  at System.Collections.ObjectModel.Collection`1[T].Clear () [0x00014] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Collections/ObjectModel/Collection.cs:81
  at MediaManager.Queue.MediaQueue.Clear () [0x00000] in Z:\Documents\OpenSource\XamarinMediaManager\MediaManager\Queue\MediaQueue.cs:173
  at MediaManager.MediaManagerBase.PrepareQueueForPlayback (System.Collections.Generic.IEnumerable`1[T] mediaItems) [0x00008] in Z:\Documents\OpenSource\XamarinMediaManager\MediaManager\MediaManagerBase.cs:282
  at MediaManager.MediaManagerBase.PrepareQueueForPlayback (MediaManager.Library.IMediaItem mediaItem) [0x00000] in Z:\Documents\OpenSource\XamarinMediaManager\MediaManager\MediaManagerBase.cs:275
  at MediaManager.MediaManagerBase.Play (System.IO.FileInfo file) [0x0009d] in Z:\Documents\OpenSource\XamarinMediaManager\MediaManager\MediaManagerBase.cs:253
  at  XXX.ViewModels.PlayerViewModel.PlayAsync (XXX.ViewModels.PlaylistItemViewModel item) [0x001f1] in D:\Projects\XXX\ViewModels\PlayerViewModel.cs:118
  at  XXX.ViewModels.PlayerViewModel.PlayNextAsync () [0x00084] in D:\Projects\XXX\ViewModels\PlayerViewModel.cs:134
  at  XXX.ViewModels.PlayerViewModel.OnMediaItemFinished (System.Object sender, MediaManager.Media.MediaItemEventArgs e) [0x00020] in D:\Projects\XXX\ViewModels\PlayerViewModel.cs:31
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.1(intptr,intptr)
  at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.1(intptr,intptr)
--- End of stack trace from previous location where exception was thrown ---

  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <89755ea61d9c4ae0a40ce90b872c9e2d>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <89755ea61d9c4ae0a40ce90b872c9e2d>:0
  at Java.Lang.Throwable.get_Message () [0x0000a] in <a54fd02a94254b8f91efc9ea3cec736c>:0
  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException
at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
at com.google.android.exoplayer2.ui.PlayerNotificationManager.setPlayer(PlayerNotificationManager.java:457)
```

**Platform:** 
- [X] :robot: Android

**Comment by danieeis** [comment]
I had the same bug, is like the notification manager, then the state exception occurs.

The reason seems to be this line of code. This exception happened to me and when I removed this line everything went back to normal:

`CrossMediaManager.Current.Notification.Enabled = true;`

Stacktrace:

`[mono] java.lang.IllegalStateException
[mono] 	at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalStateException: Exception of type 'Java.Lang.IllegalStateException' was thrown.
[mono-rt]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <42748fcc36b74733af2d9940a8f3cc8e>:0 
[mono-rt]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <42748fcc36b74733af2d9940a8f3cc8e>:0 
[mono]   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean prese9aaf6028d6e459c77>:0 
[mono-rt]   at MediaManager.Platforms.Android.Notifications.NotificationManager.set_Player (Com.Google.Android.Exoplayer2.IPlayer value) [0x00011] in <280b3e25152a47bdb46636cb6dd04e41>:0 
[mono-rt]   at MediaManager.Platforms.Android.Notifications.NotificationManager.set_Enabled (System.Boolean value) [0x0001b] in <280b3e25152a47bdb46636cb6dd04e41>:0 
[mono-rt]   at App.Code.Custom.Controls.MyVideoView..ctor () [0x00074] in <36655ce6b0904fa1a0269b3f49891449>:0 
[mono-rt]   at App.Code.Custom.Formats.VideoPlayerWithList_01.Open () [0x00075] in <36655ce6b0904fa1a0269b3f49891449>:0 
[mono-rt]   at App.Code.Custom.Formats.VideoPlayerWithList_01.Init () [0x00357] in <36655ce6b0904fa1a0269b3f49891449>:0 
[mono-rt]   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <0381c8f952fb47759ee29160e807b17d>:0 
[mono-rt]   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <0381c8f952fb47759ee29160e807b17d>:0 
[mono-rt]   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <0381c8f952fb47759ee29160e807b17d>:0 
[mono-rt]   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <0381c8f952fb47759ee29160e807b17d>:0 
[mono-rt]  12-03 00:56:59.028 E/mono-rt ( 7429):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <0381c8f952fb47759ee29160e807b17d>:0 
[mono-rt]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[mono-rt] java.lang.IllegalStateException
[mono-rt] 	at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
[mono-rt] 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.setPlayer(PlayerNotificationManager.java:673)
[mono-rt] `
